dist: bionic
language: cpp
os: linux

before_install:
  - sudo dpkg --add-architecture armhf
    # ubuntu screws up from adding armhf, so we have to tell it what repos to exclude armhf from

  - echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main restricted" > /etc/apt/sources.list
  - echo "deb-src [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main restricted" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted " >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic universe" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic universe" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic-updates universe" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic-updates universe" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic multiverse" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic multiverse" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic-updates multiverse" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64]  http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security main restricted" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security main restricted" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security universe" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security universe" >>  /etc/apt/sources.list
  - echo "deb [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security multiverse" >>  /etc/apt/sources.list
  - echo "deb-src [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security multiverse" >>  /etc/apt/sources.list
  - echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic main universe" >>  /etc/apt/sources.list
  - echo "deb [arch=armhf]  http:// eoan main universe" >> /etc/apt/sources.list
  
  - sudo apt update
  - sudo apt install python3-pip python3-dev
  - sudo apt install -y gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf libsfml-dev:armhf libncurses5-dev:armhf libyaml-cpp-dev:armhf cmake || sudo apt install -f 
  #- sudo -H python3 -m pip install --upgrade pip wheel setuptools
  #- sudo -H python3 -m pip install conan
  - wget https://archive.raspberrypi.org/debian/pool/main/w/wiringpi/wiringpi_2.50_armhf.deb
  - sudo dpkg -i wiringpi_2.50_armhf.deb


install: echo "install"

script:
  - echo "First test"
  #- conan install .
  - wget -O rf24.tar.gz https://github.com/nRF24/RF24/archive/v1.3.3.tar.gz
  - tar -xzf  rf24.tar.gz
  - ( cd RF24-1.3.3; ./configure --driver=wiringPi; sudo make install; )
