dist: trusty
language: cpp
os: linux
arch:
  - armhf
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++-8
      - libsfml-dev
      - libncurses-dev
      - libyaml-cpp-dev
      - cmake

script:
  - echo "First test"
