dist: trusty
language: cpp
os: linux
arch:
  - armhf
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - arm-linux-gnueabihf-gcc
      - arm-linux-gnueabihf-g++-8
      - libsfml-dev:armhf
      - libncurses-dev:armhf
      - libyaml-cpp-dev:armhf
      - cmake

before_install:
  - sudo dpkg --add-architecture armhf        
script:
  - echo "First test"
