dist: bionic
language: cpp
os: linux

before_install:
  - sudo dpkg --add-architecture armhf
    # ubuntu screws up from adding armhf, so we have to tell it what repos to exclude armhf from
  - sudo sed -i 's+deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic main restricted+deb [arch-amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic main restricted+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic main restricted+deb-src [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic main restricted+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates main restricted+deb [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates main restricted+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates main restricted+deb-src [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates main restricted+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic universe+deb [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic universe+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic universe+deb-src [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic universe+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates universe+deb [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates universe+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates universe+deb-src [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates universe+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic multiverse+deb [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic multiverse+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic multiverse+deb-src [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic multiverse+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates multiverse+deb [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates multiverse+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates multiverse+deb-src [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-updates multiverse+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse+deb [arch=amd64]http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse+deb-src [arch=amd64] http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://security.ubuntu.com/ubuntu bionic-security main restricted+deb [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security main restricted+g' /etc/apt/sources.list 
  - sudo sed -i 's+deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted+deb-src [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security main restricted+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://security.ubuntu.com/ubuntu bionic-security universe+deb [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security universe+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://security.ubuntu.com/ubuntu bionic-security universe+deb-src [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security universe+g' /etc/apt/sources.list
  - sudo sed -i 's+deb http://security.ubuntu.com/ubuntu bionic-security multiverse+deb [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security multiverse+g' /etc/apt/sources.list
  - sudo sed -i 's+deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse+deb-src [arch=amd64] http://security.ubuntu.com/ubuntu bionic-security multiverse+g' /etc/apt/sources.list
  - sudo echo -e "deb [arch=armhf] http://ports.ubuntu.com/ bionic main universe" >> /etc/apt/sources.list


  - cat /etc/apt/sources.list
  - ls /etc/apt/sources.list.d/
  - cat /etc/apt/sources.list.d/*
  - sudo apt update
  - sudo apt install gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf libsfml-dev:armhf libncurses-dev:armhf libyaml-cpp-dev:armhf cmake

install: echo "install"

script:
  - echo "First test"
#  - conan install .
  - wget -O rf24.tar.gz https://github.com/nRF24/RF24/archive/v1.3.3.tar.gz
  - tar -xzf  rf24.tar.gz
  - ( cd RF24-1.3.3; ./configure --driver=wiringPi; sudo make install; )
