dist: bionicy
language: cpp
os: linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - arm-linux-gnueabihf-gcc-8
      - arm-linux-gnueabihf-g++-8
      - libsfml-dev:armhf
      - libncurses-dev:armhf
      - libyaml-cpp-dev:armhf
      - cmake
before_install:
  - dpkg --add-architecture armhf
  - sudo apt update
#before_instal:
  #- sudo -H python3 -m pip install --upgrade pip wheel setuptools
install:

script:
  - echo "First test"
#  - conan install .
  - wget -O rf24.tar.gz https://github.com/nRF24/RF24/archive/v1.3.3.tar.gz
  - tar -xzf  rf24.tar.gz
  - ( cd RF24-1.3.3; ./configure --driver=wiringPi; sudo make install; )
