dist: bionicy
language: cpp
os: linux
arch:
  - armhf
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++-8
      - libsfml-dev
      - libncurses-dev
      - libyaml-cpp-dev
      - cmake
      - python3
      - python3-pip

install:
  - wget -O tmp_conan.deb https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_20_5.deb
  - sudo dpkg -i tmp_conan.deb
  - sudo apt install -f
  - conan user

script:
  - echo "First test"
  - conan install .
  - wget -O rf24.tar.gz https://github.com/nRF24/RF24/archive/v1.3.3.tar.gz
  - tar -xzf  rf24.tar.gz
  - ( cd RF24-1.3.3; ./configure --driver=wiringPi; sudo make install; )
