dist: bionicy
language: cpp
os: linux
arch:
  - armhf
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++-8
      - libsfml-dev
      - libncurses-dev
      - libyaml-cpp-dev
      - cmake
      - python3
      - python3-pip
      - python3-dev

before_instal:
  - python3 -m pip install --upgrade pip wheel setuptools
install:
  - python3 -m pip install conan
  - conan user

script:
  - echo "First test"
  - conan install .
  - wget -O rf24.tar.gz https://github.com/nRF24/RF24/archive/v1.3.3.tar.gz
  - tar -xzf  rf24.tar.gz
  - ( cd RF24-1.3.3; ./configure --driver=wiringPi; sudo make install; )
